# Http服务器配置
server:
  mode: debug
  # 端口
  port: 8080
  # 请求缓存时间1秒
  cache: 1
  # 令牌桶容量，QPS最大值
  limit: 10000
  # 令牌桶每秒放行
  rate: 0.2
  # 秒为单位
  # 读取整个请求的超时时间
  readTimeout: 10000
  # 写入响应体的超时时间
  writeTimeout: 10000
  # 读取请求头的超时时间
  readHeaderTimeout: 10000
  # Keep-alive连接复用的超时时间
  idleTimeout: 10000
  # Multipart最大内存 50MB
  multipartMemory: 52428800
  # 请求头最大大小 3MB
  maxHeaderBytes: 3145728
  # 静态地址
  static: /static

# 国际化配置
i18n:
  dir: ./lang
  suffix: .properties

# Zap日志配置
zap:
  prefix: Lite-Blog-Server
  timeFormat: 2006/01/02 - 15:04:05.00000
  level: debug
  caller: true
  stackTrace: false
  encode: console
  # 日志输出到哪里 file | console | both
  writer: both
  logFile:
    # 20MB
    maxSize: 20
    # 备份次数
    backups: 5
    # 压缩
    compress: true
    # 输出
    output:
      - "./log/output.log"

# 数据库配置
database:
  main:
    enable: true
    type: Mysql
    ip: 192.168.48.134
    port: 3306
    dbName: liteserver
    config: charset=utf8mb4&parseTime=True&loc=Local
    username: root
    password: wyh246859
    maxIdleCons: 20
    maxOpenCons: 20

#Redis配置
redis:
  ip: 192.168.48.134
  port: 6379
  Password: wyh246859
  options:
    maxRetries: 3
    minIdleConns: 6

#Jwt配置
jwt:
  acSign: vegetable-programmer-access-token
  reSign: vegetable-programmer-refresh-token
  issuer: lite-blog-server
  acExp: 2
  acAlo: 10
  reExp: 120

# 邮件配置
mail:
  host: smtp.exmail.qq.com
  port: 465
  username: vegetable-programmer@halfiisland.com
  password: Wyh246859
  expire: 5
  limit: 1