# Http服务器配置
server:
  port: 8080
  mode: dev

# Zap日志配置
zap:
  level: -1
  development: true
  caller: true
  encode: json
  outputPath:
    - "stdout"
    - "./log/log.json"
  errOutputPath:
    - "stdout"
    - "./log/error.json"

# 数据库配置
database:
  main:
    enable: true
    type: Mysql
    ip: 192.168.48.134
    port: 3306
    dbName: liteserver
    config: charset=utf8mb4&parseTime=True&loc=Local
    username: root
    password: wyh246859
    maxIdleCons: 20
    maxOpenCons: 20

#Redis配置
redis:
  ip: 192.168.48.134
  port: 6379
  Password: wyh246859
  options:
    maxRetries: 3
    minIdleConns: 6

#Jwt配置
jwt:
  signKey: vegetable-programmer
  accessExpiredTime: 2
  refreshExpiredTime: 24*5
  issuer: lite-blog-server

